const C=window.SERA_CONFIG; let token=localStorage.getItem('sera_token')||'demo-token'; let user=JSON.parse(localStorage.getItem('sera_user')||'null');
let supa=null; if(C.SUPABASE_URL.startsWith('http')&&!C.SUPABASE_ANON_KEY.startsWith('YOUR_')) supa=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_ANON_KEY);
const api=async(p,o={})=>{
  const r=await fetch(C.API_BASE+p,{...o,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(o.headers||{})}});
  if(!r.ok){let detail='API '+r.status;try{const j=await r.json();detail=j.detail||detail}catch{};throw Error(detail)}
  return r.json();
};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function boot(){
  try{
    if(supa){
      const {data:{session}}=await supa.auth.getSession();
      if(session){token=session.access_token;user=session.user;localStorage.setItem('sera_token',token);localStorage.setItem('sera_user',JSON.stringify(user));}
      supa.auth.onAuthStateChange((_event,session)=>{
        if(session){token=session.access_token;user=session.user;localStorage.setItem('sera_token',token);localStorage.setItem('sera_user',JSON.stringify(user));dashboard().catch(showAppError)}
      });
    }
    if(!user){login();} else await dashboard();
  }catch(e){showAppError(e)}
}
function showAppError(e){document.getElementById('app').innerHTML=`<main class=\"auth\"><div class=\"card authcard\"><div class=\"brand\">SERA<span>4.2</span></div><h1>Connection problem</h1><p>${esc(e.message||'Unable to load SERA')}</p><button class=\"primary\" onclick=\"location.reload()\">Retry</button><small>Check that FastAPI is running and Supabase credentials are configured.</small></div></main>`}
function login(){document.getElementById('app').innerHTML=`<main class="auth"><div class="card authcard"><div class="brand">SERA<span>4.2</span></div><h1>Dynamic well-being intelligence</h1><p>Diary + contextual signals + early-warning alerts, with user-controlled sensing.</p><button class="primary" onclick="googleLogin()">Continue with Google</button><button class="ghost" onclick="demoLogin()">Use local demo</button><small>For production, configure Supabase Google OAuth. Browser/screen monitoring is opt-in and never silently enabled.</small></div></main>`}
async function googleLogin(){if(!supa)return alert('Configure SUPABASE_URL and SUPABASE_ANON_KEY in frontend/config.js first.'); const {error}=await supa.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}}); if(error)alert(error.message)}
function demoLogin(){user={id:'demo-user',email:'demo@sera.local',user_metadata:{name:'Demo User'}};token='demo-token';localStorage.setItem('sera_user',JSON.stringify(user));localStorage.setItem('sera_token',token);dashboard()}
async function dashboard(){try{const d=await api('/api/dashboard');const latest=d.checkins[0];const score=latest?.distress??0;document.getElementById('app').innerHTML=`<div class="shell"><aside><div class="brand">SERA<span>4.2</span></div><nav><button onclick="dashboard()">Overview</button><button onclick="checkin()">Daily diary</button><button onclick="contextPage()">Live context</button><button onclick="alerts()">Alerts <b>${d.alerts.length}</b></button><button onclick="setup()">Companion setup</button></nav><div class="profile">${esc(user.email||'User')}<button onclick="logout()">Sign out</button></div></aside><section class="main"><header><div><p class="eyebrow">PERSONAL EARLY-WARNING SYSTEM</p><h1>Good to see you.</h1></div><div class="live"><i></i> API live</div></header><div class="grid"><div class="hero card"><div><span class="label">CURRENT DISTRESS</span><div class="score">${score}</div><div class="status ${score>=70?'high':score>=45?'med':'low'}">${score>=70?'HIGH':score>=45?'MEDIUM':'LOW'} · ${latest?.created_at?'updated '+new Date(latest.created_at).toLocaleTimeString(): 'no check-in yet'}</div></div><div class="ring" style="--p:${score*3.6}deg"></div></div><div class="card"><span class="label">TODAY</span><h2>${d.checkins.length} check-ins</h2><p>Context events: ${d.context.length}</p><button class="primary" onclick="checkin()">New check-in</button></div><div class="card wide"><span class="label">TRAJECTORY</span><div class="chart">${d.checkins.slice(0,10).reverse().map(x=>`<span style="height:${Math.max(8,x.distress)}%" title="${x.distress}"></span>`).join('')}</div><p>SERA compares each signal against your recent history rather than treating one message as a diagnosis.</p></div><div class="card"><span class="label">RECENT ALERTS</span>${d.alerts.slice(0,4).map(a=>`<div class="alertrow"><strong>${a.level}</strong><span>${new Date(a.created_at).toLocaleString()}</span></div>`).join('')||'<p>No alerts.</p>'}</div></div></section></div>`}catch(e){showAppError(e)}}
function checkin(){document.getElementById('app').innerHTML=`<div class="shell"><aside>${side()}</aside><section class="main"><header><div><p class="eyebrow">DAILY DIARY</p><h1>How has your day been?</h1></div></header><div class="card form"><label>Diary</label><textarea id="body" placeholder="Write naturally about your day, studies, relationships, family, work, money, sleep or anything affecting you..."></textarea><div class="row"><label>Stress <input id="stress" type="range" min="0" max="10" value="5"><b id="sv">5</b></label><label>Mood <input id="mood" type="range" min="0" max="10" value="5"><b id="mv">5</b></label></div><div class="row"><label>Sleep hours <input id="sleep" type="number" min="0" max="16" value="7"></label><label>Energy <input id="energy" type="range" min="0" max="10" value="5"></label></div><div class="chips">${['studies','relationship','family','money','bullying','blackmail','work','loneliness'].map(x=>`<button onclick="this.classList.toggle('sel')" data-factor="${x}">${x}</button>`).join('')}</div><div class="row"><button class="ghost" onclick="startSpeech()">🎙 Speech-to-text</button><button class="primary" onclick="submitCheckin()">Analyze & update SERA</button></div><p id="msg"></p></div></section></div>`;['stress','mood'].forEach(id=>document.getElementById(id).oninput=()=>document.getElementById(id[0]+'v').textContent=document.getElementById(id).value)}
function side(){return `<div class="brand">SERA<span>4.2</span></div><nav><button onclick="dashboard()">Overview</button><button onclick="checkin()">Daily diary</button><button onclick="contextPage()">Live context</button><button onclick="alerts()">Alerts</button><button onclick="setup()">Companion setup</button></nav>`}
async function submitCheckin(){const factors=[...document.querySelectorAll('.chips .sel')].map(x=>x.dataset.factor);const r=await api('/api/checkins',{method:'POST',body:JSON.stringify({body:document.getElementById('body').value,mood:+document.getElementById('mood').value,stress:+document.getElementById('stress').value,sleep:+document.getElementById('sleep').value,energy:+document.getElementById('energy').value,factors})});document.getElementById('msg').innerHTML=`<div class="result ${r.level.toLowerCase()}"><b>${r.level} · ${r.score}</b><p>Trend: ${r.trend}</p><p>${r.reasons.join(' · ')||'No major risk signals detected.'}</p>${r.level==='HIGH'?'<strong>Human review recommended.</strong>':''}</div>`}
function startSpeech(){if(!('SpeechRecognition'in window||'webkitSpeechRecognition'in window))return alert('Speech recognition is not supported in this browser.');const R=window.SpeechRecognition||window.webkitSpeechRecognition;const x=new R();x.continuous=false;x.interimResults=false;x.onresult=e=>document.getElementById('body').value+=(document.getElementById('body').value?' ':'')+e.results[0][0].transcript;x.start()}
async function contextPage(){const d=await api('/api/dashboard');document.getElementById('app').innerHTML=`<div class="shell"><aside>${side()}</aside><section class="main"><header><div><p class="eyebrow">LIVE CONTEXT</p><h1>Consent-based sensing</h1></div><div class="live"><i></i> polling</div></header><div class="grid"><div class="card wide"><h2>Recent context events</h2>${d.context.map(x=>`<div class="context"><strong>${esc(x.category)}</strong><span>${esc(x.source)}</span><small>${new Date(x.created_at).toLocaleString()}</small></div>`).join('')||'<p>No events yet. Install/enable the companion to send coarse browser categories.</p>'}</div><div class="card"><h2>Privacy boundary</h2><p>SERA receives coarse activity categories only. No passwords, private messages, microphone or camera are silently captured.</p><button class="primary" onclick="setup()">Set up companion</button></div></div></section></div>`}
async function alerts(){const d=await api('/api/dashboard');document.getElementById('app').innerHTML=`<div class="shell"><aside>${side()}</aside><section class="main"><header><div><p class="eyebrow">ALERT CENTER</p><h1>Early-warning queue</h1></div></header><div class="card">${d.alerts.map(a=>`<article class="bigalert ${a.level.toLowerCase()}"><div><span>${a.level}</span><h2>${a.title}</h2><p>Score ${a.score} · ${new Date(a.created_at).toLocaleString()}</p><ul>${JSON.parse(a.reasons||'[]').map(r=>`<li>${esc(r)}</li>`).join('')}</ul></div><button class="primary" onclick="support('${a.level}')">Request human support</button></article>`).join('')||'<p>No open alerts.</p>'}</div></section></div>`}
async function support(level='normal'){const note=prompt('Optional note for the support team:','Please review my current SERA alert.');if(note===null)return;await api('/api/support',{method:'POST',body:JSON.stringify({priority:level.toLowerCase(),note})});alert('Support request recorded.')}
function setup(){document.getElementById('app').innerHTML=`<div class="shell"><aside>${side()}</aside><section class="main"><header><div><p class="eyebrow">COMPANION</p><h1>Connect your context</h1></div></header><div class="grid"><div class="card wide"><h2>Browser Companion</h2><p>Install the unpacked extension during development or the published extension in production. It requires explicit user permission and sends only coarse categories.</p><ol><li>Download the extension package.</li><li>Open <code>chrome://extensions</code>.</li><li>Enable Developer mode for the MVP.</li><li>Load unpacked → select the <code>extension</code> folder.</li><li>Open the extension and enable monitoring.</li></ol><a class="primary link" href="../extension/" download>Extension package folder</a></div><div class="card"><h2>Screen / audio</h2><p>Web apps cannot silently read the desktop or microphone. Use explicit browser permissions or user-selected uploads. V4.2 stores metadata and local upload references; it never enables covert surveillance.</p><button class="ghost" onclick="alert('For production, add a user-triggered screen/audio capture flow using browser permission APIs.')">View consent model</button></div></div></section></div>`}
async function logout(){if(supa)await supa.auth.signOut();localStorage.clear();location.reload()}
boot();
setInterval(()=>{if(user) { const el=document.querySelector('.live'); if(el)el.title='Live monitoring enabled';}},5000);
